apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  tls:
  - hosts: 
    - "*.smart.home"
    secretName: tls-cert
  rules:
  - host: registry.smart.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
